language:         c
os:
  # - linux
  - osx
env:
  - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"
sudo:             required
compiler:
  - gcc
addons:
  apt:
    packages:
    - gfortran

before_install:
  # - sudo apt-get install gfortran
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then pip install numpy --user   ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then pip2 install numpy --user   ; fi
  - |
    # if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then
    #   brew update &> /dev/null
    #   brew cask uninstall --force oclint
    #   brew install gcc
    # fi
    if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then
      brew cask uninstall --force oclint
      brew install gcc
    fi


script:
  - make exe

before_deploy:
  # Set up git user name and tag this commit
  - git config --local user.name "sunt05"
  - git config --local user.email "sunting.05@gmail.com"
  - git tag "$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"

deploy:
  provider:       releases
  api_key:        "9d94430ed4c62048a5f5c59ef6d9035ddc84369d"
  file:           "./ReleaseRepo/build/macOS/SUEWS_V2018a"
    # - "./SUEWS-SourceCode/Linux/SUEWS_V2018a"
  skip_cleanup:   true
  on:
    all_branches: true
