language: c
sudo: required
before_install:
  - sudo apt-get install gfortran
  - pip install numpy

script:
  - make

deploy:
  provider: releases
  # api_key: "GITHUB OAUTH TOKEN"
  file: "./SUEWS-SourceCode/SUEWS_V2018a"
  skip_cleanup: true
  on:
    tags: true
