language: c
sudo: required
addons:
  apt:
    packages:
    - gfortran

before_install:
  # - sudo apt-get install gfortran
  - pip install numpy --user

script:
  - make exe

deploy:
  provider: releases
  # api_key: "GITHUB OAUTH TOKEN"
  file: "./SUEWS-SourceCode/SUEWS_V2018a"
  skip_cleanup: true
