language:        c
sudo:            required
addons:
  apt:
    packages:
    - gfortran

before_install:
  # - sudo apt-get install gfortran
  - pip install numpy --user

script:
  - make exe

before_deploy:
  # Set up git user name and tag this commit
  - git config --local user.name "sunt05"
  - git config --local user.email "sunting.05@gmail.com"
  - git tag "$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"

deploy:
  provider:      releases
  api_key:       "d84ab79a5f43f2db2ae4"
  file:          "./SUEWS-SourceCode/SUEWS_V2018a"
  skip_cleanup:  true
  on:
    tags:        false
    branch:      AnOHM
